baseurl = "https://waterslog.me/"
title = "Build My Passive Income"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

enableRobotsTXT = true
canonifyURLs = true

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "↑"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "WATERS"
    info = "看看这个世界"
    description = "Self-management + IT technology + Investment transactions = build my passive income"
    keywords = "life,dev,trade,passive income,money,developer,Self-management,IT technology,investment transactions"
    avatarurl = "https://cdn.sspai.com/2019/03/07/22e042dd797cd86f72ede915501282cd.jpg"
    logoImg = "images/bmpi_logo.jpg"
    header = "WATERS. BLOG"

    twitter = "_MartinWaters"
    github = "wwWaters"
    telegram = "wwWaters"
    zhihu = "WATERS"

    favicon_32 = "images/f/favicon-32x32.png"
    favicon_16 = "images/f/favicon-16x16.png"

    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    series = true

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = true
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-1886683614725279"
    googleAnalytics = "UA-154678195-1"

# Comments on github issue
[params.utteranc]
    repo = "bmpi-dev/bmpi.dev"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/wwWATERS"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/_MartinWaters"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 3
    url = "https://t.me/s/wwWaters"
[[params.social]]
    name = "WeChat"
    icon = "fab fa-weixin"
    weight = 4
    url = "https://img.bmpi.dev/755b406f-43ae-e382-e13c-547116d3e7d5.png"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "index.xml"

[languages]

    [languages.zh-cn]
        languagename = "Chinese"
        title = "WATERS's Blog"

        [languages.zh-cn.params]
            author = "WATERS"
            info = "看看这个世界"
            description = "1"
            keywords = "1"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]

            [[languages.zh-cn.menu.main]]
                name = "About"
                weight = 1
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "Life"
                weight = 2
                url  = "/life/"
            [[languages.zh-cn.menu.main]]
                name = "App"
                weight = 3
                url  = "/app/"
            [[languages.zh-cn.menu.main]]
                name = "Code"
                weight = 4
                url  = "/code/"
